rule currency{
    meta:
        author = "QYDD"
        version = "0.1"
        shortcoming = "The number of strings should be more accurate."
        description = "Detects bank trojans that are related with digital currency business"
    strings:
        $currency_name1 = "Bitcoin"                                                               
        $currency_name2 = "Litecoin"                                  
        $currency_name3 = "Namecoin"                                  
        $currency_name4 = "Peercoin"                                  
        $currency_name5 = "Dogecoin"                                  
        $currency_name6 = "Gridcoin"                                  
        $currency_name7 = "Primecoin"                                 
        $currency_name8 = "Ripple"                                    
        $currency_name9 = "Nxt"                                       
        $currency_name10 = "Auroracoin"                                
        $currency_name11 = "Dash"                                      
        $currency_name12 = "NEO"                                       
        $currency_name13 = "MazaCoin"                                 
        $currency_name14 = "Monero"                                    
        $currency_name15 = "NEM"                                       
        $currency_name16 = "PotCoin"                                   
        $currency_name17 = "Titcoin"                                   
        $currency_name18 = "Verge"                                     
        $currency_name19 = "Stellar"                                   
        $currency_name20 = "Vertcoin"                                  
        $currency_name21 = "Ether Ethereum"                            
        $currency_name22 = "Ethereum Classic"
        $currency_name23 = "Nano"                                      
        $currency_name24 = "Tether"                                    
        $currency_name25 = "Zcash"                                     
        $currency_name26 = "Bitcoin Cash"                              
        $currency_name27 = "EOS.IO"                                    
        $currency_name28 = "XRP"                                       
        $currency_name29 = "Tether"                                    
        $currency_name30 = "BitcoinCash"                               
        $currency_name31 = "Bitcoin SV"                                
        $currency_name32 = "Binance Coin"                              
        $currency_name33 = "Tezos"                                     
        $currency_name34 = "UNUS SED LEO"                              
        $currency_name35 = "Monero"                                    
        $currency_name36 = "Stellar Lumens"                            
        $currency_name37 = "Cardano"                                   
        $currency_name38 = "TRON"                                      
        $currency_name39 = "Chainlink"                                 
        $currency_name40 = "Huobi Token"                               
        $currency_name41 = "USD Coin"                                  
        $currency_name42 = "Crypto.com Coin"                           
        $currency_name43 = "Dash"                                      
        $currency_name44 = "Ethereum Classic"                          
        $currency_name45 = "Hedge Trade"                               
        $currency_name46 = "Neo"                                       
        $currency_name47 = "IOTA"                                      
        $currency_name48 = "Cosmos"                                    
        $currency_name49 = "NEM"                                       
        $currency_name50 = "Maker"                                     
        $currency_name51 = "Zcash"                                     
        $currency_name52 = "Paxos Standard"                            
        $currency_name53 = "OKB"                                       
        $currency_name54 = "Ontology"                                  
        $currency_name55 = "FTX Token"                                 
        $currency_name56 = "Dogecoin"                                  
        $currency_name57 = "Basic Attention Token"                     
        $currency_name58 = "Binance USD"                               
        $currency_name59 = "VeChain"                                   
        $currency_name60 = "EDC Blockchain"                            
        $currency_name61 = "TrueUSD"                                   
        $currency_name62 = "Bitcoin Gold"                              
        $currency_name63 = "Lisk"                                      
        $currency_name64 = "Hedera Hashgraph"                          
        $currency_name65 = "Decred"                                    
        $currency_name66 = "Qtum"                                      
        $currency_name67 = "Augur"                                     
        $currency_name68 = "ZB Token"                                  
        $currency_name69 = "ICON"                                      
        $currency_name70 = "Synthetix Network Token"                   
        $currency_name71 = "Algorand"                                  
        $currency_name72 = "0x"                                        
        $currency_name73 = "Bitcoin Diamond"                           
        $currency_name74 = "Ravencoin"                                 
        $currency_name75 = "Waves"                                     
        $currency_name76 = "Dai"                                       
        $currency_name77 = "MonaCoin"                                  
        $currency_name78 = "Kyber Network"                             
        $currency_name79 = "KuCoin Shares"                             
        $currency_name80 = "MCO"                                       
        $currency_name81 = "OmiseGO"                                   
        $currency_name82 = "Enjin Coin"                                
        $currency_name83 = "Steem"                                     
        $currency_name84 = "Status"                                    
        $currency_name85 = "Nano"                                      
        $currency_name86 = "THETA"                                     
        $currency_name87 = "DxChain Token"                             
        $currency_name88 = "Nexo"                                      
        $currency_name89 = "Bytom"                                     
        $currency_name90 = "Nervos Network"                            
        $currency_name91 = "DigiByte"                                  
        $currency_name92 = "Holo"                                      
        $currency_name93 = "Siacoin"                                   
        $currency_name94 = "ABBC Coin"                                 
        $currency_name95 = "DigixDAO"                                  
        $currency_name96 = "Horizen"

        $symbol1 = "BTC" nocase
        $symbol2 = "XBT" nocase
        $symbol3 = "LTC" nocase
        $symbol4 = "NMC" nocase
        $symbol5 = "PPC" nocase
        $symbol6 = "DOGE" nocase
        $symbol7 = "XDG" nocase
        $symbol8 = "GRC" nocase
        $symbol9 = "XPM" nocase
        $symbol10 = "XRP" nocase
        $symbol11 = "NXT" nocase
        $symbol12 = "AUR" nocase
        $symbol13 = "DASH" nocase
        $symbol14 = "NEO" nocase
        $symbol15 = "MZC" nocase
        $symbol16 = "XMR" nocase
        $symbol17 = "XEM" nocase
        $symbol18 = "POT" nocase
        $symbol19 = "TIT" nocase
        $symbol20 = "XVG" nocase
        $symbol21 = "XLM" nocase
        $symbol22 = "VTC" nocase
        $symbol23 = "ETH" nocase
        $symbol24 = "Nano" nocase
        $symbol25 = "USDT" nocase
        $symbol26 = "ZEC" nocase
        $symbol27 = "BCH" nocase
        $symbol28 = "EOS" nocase
        $symbol29 = "XRP" nocase
        $symbol30 = "USDT" nocase
        $symbol31 = "BCH" nocase
        $symbol32 = "BSV" nocase
        $symbol33 = "BNB" nocase
        $symbol34 = "XTZ" nocase
        $symbol35 = "LEO" nocase
        $symbol36 = "XMR" nocase
        $symbol37 = "XLM" nocase
        $symbol38 = "ADA" nocase
        $symbol39 = "TRX" nocase
        $symbol40 = "LNK" nocase
        $symbol41 = "HT" nocase
        $symbol42 = "USDC" nocase
        $symbol43 = "CRO" nocase
        $symbol44 = "DASH" nocase
        $symbol45 = "ETC" nocase
        $symbol46 = "HEDG" nocase
        $symbol47 = "NEO" nocase
        $symbol48 = "MIOTA" nocase
        $symbol49 = "ATOM" nocase
        $symbol50 = "XEM" nocase
        $symbol51 = "MKR" nocase
        $symbol52 = "ZEC" nocase
        $symbol53 = "PAX" nocase
        $symbol54 = "OKB" nocase
        $symbol55 = "ONT" nocase
        $symbol56 = "FTT" nocase
        $symbol57 = "DOGE" nocase
        $symbol58 = "BAT" nocase
        $symbol59 = "BUSD" nocase
        $symbol60 = "VET" nocase
        $symbol61 = "EDC" nocase
        $symbol62 = "TUSD" nocase
        $symbol63 = "BTG" nocase
        $symbol64 = "LSK" nocase
        $symbol65 = "HBAR" nocase
        $symbol66 = "DCR" nocase
        $symbol67 = "QTUM" nocase
        $symbol68 = "REP" nocase
        $symbol69 = "ZB" nocase
        $symbol70 = "ICX" nocase
        $symbol71 = "SNX" nocase
        $symbol72 = "ALGO" nocase
        $symbol73 = "ZRX" nocase
        $symbol74 = "BCD" nocase
        $symbol75 = "RVN" nocase
        $symbol76 = "WAVES" nocase
        $symbol77 = "DAI" nocase
        $symbol78 = "MONA" nocase
        $symbol79 = "KNC" nocase
        $symbol80 = "KCS" nocase
        $symbol81 = "MCO" nocase
        $symbol82 = "OMG" nocase
        $symbol83 = "ENJ" nocase
        $symbol84 = "STEEM" nocase
        $symbol85 = "SNT" nocase
        $symbol86 = "NANO" nocase
        $symbol87 = "THETA" nocase
        $symbol88 = "DX" nocase
        $symbol89 = "NEXO" nocase
        $symbol90 = "BTM" nocase
        $symbol91 = "CKB" nocase
        $symbol92 = "DGB" nocase
        $symbol93 = "HOT" nocase
        $symbol94 = "SC" nocase
        $symbol95 = "ABBC" nocase
        $symbol96 = "DGD" nocase
        $symbol97 = "ZEN" nocase
    condition:
        2 of ($currency_name*) or 2 of ($symbol*)
} 